import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // create a CSS variable
});

export const metadata = {
  title: "NextStep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-full min-h-screen text-black bg-white max-w-7xl mx-auto `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
